### ISSUE TITLE
Having an error with the module

### ISSUE THREAD

**Issue by TechPro424** [ghostdevv/djs-ticketsystem#10]
```
/home/runner/MultiBot/node_modules/djs-ticketsystem/src/structures/guild.js:5
Structures.extend('Guild', Guild => {
           ^

TypeError: Cannot read properties of undefined (reading 'extend')
    at Object.<anonymous> (/home/runner/MultiBot/node_modules/djs-ticketsystem/src/structures/guild.js:5:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/runner/MultiBot/node_modules/djs-ticketsystem/src/index.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

I'm having an error after writing my `open` and `close` ticket commands

**Comment by ghostdevv** [comment]
This is due to you using v13 of discord.js, v13 support is being worked on: #9
